# Header
menu:
  home: 
  categories: categories
  archives: archives
  tags: tags
  about: about
  resume: resume
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts


# title
links_title: 友情链接
links:
  老唐的博客: http://www.dendoink.com
  songtianyi的博客: https://songtianyi.github.io 

social:
  GitHub: https://github.com/AlexiaChen
  豆瓣: https://www.douban.com/people/foo_hack/
  领英: https://www.linkedin.com/in/mathxhchen

# MathJax Support
mathjax: enable

# buid site start time
since: 2013

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
